DROP TABLE IF EXISTS RegisteredUser CASCADE;

DROP TABLE IF EXISTS Priority CASCADE;

DROP TABLE IF EXISTS Topic CASCADE;

DROP TABLE IF EXISTS Task CASCADE;

DROP TABLE IF EXISTS Task_topic CASCADE;
